### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by JodliDev**
There are some other plugins that depend on a newer version of sabre/vobject and as far as I can tell, everything seems to work fine with 4.3.5.
So please update :)

### CODE REVIEW

**Comment by JodliDev** [comment]
Ok I spoke too soon. There were some changes mentioned in <https://sabre.io/vobject/upgrade_to_4/> that I implemented.
Also, I noticed that `DateTimeImmutable`, which was implemented in PHP 5.5 is not considered when checking for an objects class, so I added it.
I am using this version of the library on my own server and have been testing it, so my PR should be ok to implement :)

**Comment by JodliDev** [comment]
Just fwi. I created a fork of your calendar plugin that adds CalDAV support (that is actually usable):
https://github.com/JodliDev/calendar

But since it uses a newer version of sabre/dav, it also needs a newer verseion of sabre/vobject.
So, I cant create a PR for my changes until this PR is accepted :)

Ill stop spamming you now ;)

**Comment by alecpl** [comment]
This is a mirror of https://git.kolab.org/diffusion/RPK/. We do not accept PRs changing the code here.

**Comment by JodliDev** [comment]
My apologies. It was the easiest route to take for me :)

I am not familiar with git platforms other than github. I can send you pull request there as well right?

**Pull request closed without merging**
